#!/bin/bash


  echo -e "\033[36m

  enable

  这个命令或者禁用内建命令或者恢复内建命令.

  如: enable -n kill 将禁用 kill 内建命令, 所以当我们调用 kill 时,使用的将是/bin/kill 外部命令.

  -a 选项将会恢复相应的内建命令,如果不带参数的话,将会恢复所有的内建命令.
  -f 选项filename 将会从适当的编译过的目标文件[6]中以共享库(DLL)的形式来加载一个
内建命令.
  \033[0m"


  echo -e "\033[35m

   autoload

    这是从 ksh 的 autoloader 命令移植过来的.一个带有"autoload"声明的函数,在它第一次被 调用的时候才会被加载.[7] 这样做会节省系统资源.

   注意: autoload 命令并不是 Bash 安装时候的核心命令的一部分.这个命令需要使用命令enable -f(见上边 enable 命令)来加载.
 \033[0m"

